#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CreatePlayer

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CreatePlayer.BP_CreatePlayer_C
// 0x0048 (0x0378 - 0x0330)
class ABP_CreatePlayer_C : public AHTCreatePlayerActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0330(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0338(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCameraComponent*                       Camera;                                            // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCapsuleComponent*                      Capsule;                                           // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnSelectEvent;                                     // 0x0350(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnUnselectEvent;                                   // 0x0360(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UAsyncAction_ListenForGameplayMessageWithSimpleMessage* Listener_Object;                   // 0x0370(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BPOnSelect();
	void BPOnUnselect();
	void ExecuteUbergraph_BP_CreatePlayer(int32 EntryPoint);
	class USkeletalMeshComponent* GetMesh();
	void OnMessageReceived_0136FA7E458F1197528BAD93F7E31078(class FName Channel, const struct FGameplayMessageSimpleMessage& Message);
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CreatePlayer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CreatePlayer_C")
	}
	static class ABP_CreatePlayer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CreatePlayer_C>();
	}
};
DUMPER7_ASSERTS_ABP_CreatePlayer_C;

SDK_NAMESPACE_END
