#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CreatePlayer_Female

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_CreatePlayer_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CreatePlayer_Female.BP_CreatePlayer_Female_C
// 0x0008 (0x0380 - 0x0378)
class ABP_CreatePlayer_Female_C final : public ABP_CreatePlayer_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_CreatePlayer_Female_C;           // 0x0378(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BPSetOpenState();
	void ExecuteUbergraph_BP_CreatePlayer_Female(int32 EntryPoint);
	class USkeletalMeshComponent* GetMesh();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CreatePlayer_Female_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CreatePlayer_Female_C")
	}
	static class ABP_CreatePlayer_Female_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CreatePlayer_Female_C>();
	}
};
DUMPER7_ASSERTS_ABP_CreatePlayer_Female_C;

SDK_NAMESPACE_END
