#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameData_Updater

#include "Basic.hpp"

#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GameData_Updater.BP_GameData_Updater_C
// 0x0000 (0x22F0 - 0x22F0)
class UBP_GameData_Updater_C final : public UHTGameData
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GameData_Updater_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GameData_Updater_C")
	}
	static class UBP_GameData_Updater_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GameData_Updater_C>();
	}
};
DUMPER7_ASSERTS_UBP_GameData_Updater_C;

SDK_NAMESPACE_END
