#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameStateBase

#include "Basic.hpp"

#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_GameStateBase.BP_GameStateBase_C
// 0x0010 (0x0C60 - 0x0C50)
class ABP_GameStateBase_C final : public AHTGameState
{
public:
	uint8                                         Pad_C48[0x8];                                      // 0x0C48(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0C50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GameStateBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GameStateBase_C")
	}
	static class ABP_GameStateBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_GameStateBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_GameStateBase_C;

SDK_NAMESPACE_END
