#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HTHUD

#include "Basic.hpp"

#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_HTHUD.BP_HTHUD_C
// 0x0008 (0x0CD0 - 0x0CC8)
class ABP_HTHUD_C final : public AHTHUD
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0CC8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_HTHUD_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_HTHUD_C")
	}
	static class ABP_HTHUD_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_HTHUD_C>();
	}
};
DUMPER7_ASSERTS_ABP_HTHUD_C;

SDK_NAMESPACE_END
