#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_NavigationPathActor

#include "Basic.hpp"

#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_NavigationPathActor.BP_NavigationPathActor_C
// 0x0000 (0x0708 - 0x0708)
class ABP_NavigationPathActor_C final : public ANavigationPathEffectActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_NavigationPathActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_NavigationPathActor_C")
	}
	static class ABP_NavigationPathActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_NavigationPathActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_NavigationPathActor_C;

SDK_NAMESPACE_END
