#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerControllerBase

#include "Basic.hpp"

#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PlayerControllerBase.BP_PlayerControllerBase_C
// 0x0000 (0x1B60 - 0x1B60)
class ABP_PlayerControllerBase_C final : public AHTPlayerController
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerControllerBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerControllerBase_C")
	}
	static class ABP_PlayerControllerBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlayerControllerBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_PlayerControllerBase_C;

SDK_NAMESPACE_END
