#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_UpdaterGameMode

#include "Basic.hpp"

#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_UpdaterGameMode.BP_UpdaterGameMode_C
// 0x0008 (0x03E0 - 0x03D8)
class ABP_UpdaterGameMode_C final : public AHTGameMode
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x03D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_UpdaterGameMode_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_UpdaterGameMode_C")
	}
	static class ABP_UpdaterGameMode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_UpdaterGameMode_C>();
	}
};
DUMPER7_ASSERTS_ABP_UpdaterGameMode_C;

SDK_NAMESPACE_END
