#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_UpdaterBG

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_structs.hpp"
#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass BPUI_UpdaterBG.BPUI_UpdaterBG_C
// 0x0030 (0x0F50 - 0x0F20)
class UBPUI_UpdaterBG_C final : public UHTUI_UpdaterBG
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0F20(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUICommonVideoPlayerWidget_C*           UICommonVideoPlayerWidget;                         // 0x0F28(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_49;                                          // 0x0F30(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFileMediaSource*                       UpdaterSource;                                     // 0x0F38(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UMediaPlayer*                           MediaPlayer;                                       // 0x0F40(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UFileMediaSource*                       CurrMedia;                                         // 0x0F48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void BP_PlayVideo(const class FString& VideoUrl);
	void BP_PlayVideoBGM(int32 Index_0);
	void Construct();
	void CustomEvent_EndReached();
	void Destruct();
	void ExecuteUbergraph_BPUI_UpdaterBG(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPUI_UpdaterBG_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPUI_UpdaterBG_C")
	}
	static class UBPUI_UpdaterBG_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPUI_UpdaterBG_C>();
	}
};
DUMPER7_ASSERTS_UBPUI_UpdaterBG_C;

SDK_NAMESPACE_END
