#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_Updater

#include "Basic.hpp"

#include "HTGame_structs.hpp"
#include "UMG_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPUI_Updater.BPUI_Updater_C.AdjustMediaSize
// 0x0038 (0x0038 - 0x0000)
struct BPUI_Updater_C_AdjustMediaSize final
{
public:
	struct FVector2D                              CallFunc_GetViewportSize_ReturnValue;              // 0x0000(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetViewportScale_ReturnValue;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_BreakVector2D_X;                          // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector2D_Y;                          // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue_1;    // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x002A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B[0x5];                                       // 0x002B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_AdjustMediaSize;

// Function BPUI_Updater.BPUI_Updater_C.BndEvt__BPUI_Updater_Button_Cancel_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_BndEvt__BPUI_Updater_Button_Cancel_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_BndEvt__BPUI_Updater_Button_Cancel_1_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_Updater.BPUI_Updater_C.BndEvt__BPUI_Updater_Button_Cancel_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_BndEvt__BPUI_Updater_Button_Cancel_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_BndEvt__BPUI_Updater_Button_Cancel_K2Node_ComponentBoundEvent_4_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_Updater.BPUI_Updater_C.BndEvt__BPUI_Updater_Button_Ok_1_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_BndEvt__BPUI_Updater_Button_Ok_1_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_BndEvt__BPUI_Updater_Button_Ok_1_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_Updater.BPUI_Updater_C.BndEvt__BPUI_Updater_Button_Ok_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_BndEvt__BPUI_Updater_Button_Ok_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_BndEvt__BPUI_Updater_Button_Ok_K2Node_ComponentBoundEvent_3_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_Updater.BPUI_Updater_C.BndEvt__BPUI_Updater_Button_restart_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_BndEvt__BPUI_Updater_Button_restart_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_BndEvt__BPUI_Updater_Button_restart_K2Node_ComponentBoundEvent_0_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_Updater.BPUI_Updater_C.BndEvt__UI_PatcherMainForm_AppPreviousNotice_K2Node_ComponentBoundEvent_16_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_BndEvt__UI_PatcherMainForm_AppPreviousNotice_K2Node_ComponentBoundEvent_16_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_BndEvt__UI_PatcherMainForm_AppPreviousNotice_K2Node_ComponentBoundEvent_16_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_Updater.BPUI_Updater_C.BndEvt__UI_PatcherMainForm_Button_restart_1_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_BndEvt__UI_PatcherMainForm_Button_restart_1_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_BndEvt__UI_PatcherMainForm_Button_restart_1_K2Node_ComponentBoundEvent_18_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_Updater.BPUI_Updater_C.BndEvt__UI_PatcherMainForm_Button_TryAgain_K2Node_ComponentBoundEvent_12_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_BndEvt__UI_PatcherMainForm_Button_TryAgain_K2Node_ComponentBoundEvent_12_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_BndEvt__UI_PatcherMainForm_Button_TryAgain_K2Node_ComponentBoundEvent_12_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_Updater.BPUI_Updater_C.BndEvt__UI_PatcherMainForm_ExitButton_2_K2Node_ComponentBoundEvent_14_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_BndEvt__UI_PatcherMainForm_ExitButton_2_K2Node_ComponentBoundEvent_14_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_BndEvt__UI_PatcherMainForm_ExitButton_2_K2Node_ComponentBoundEvent_14_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_Updater.BPUI_Updater_C.BndEvt__UI_PatcherMainForm_UpdateButton_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_BndEvt__UI_PatcherMainForm_UpdateButton_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature final
{
public:
	class UCommonButtonBase*                      Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_BndEvt__UI_PatcherMainForm_UpdateButton_K2Node_ComponentBoundEvent_9_CommonButtonBaseClicked__DelegateSignature;

// Function BPUI_Updater.BPUI_Updater_C.ExecuteUbergraph_BPUI_Updater
// 0x0368 (0x0368 - 0x0000)
struct BPUI_Updater_C_ExecuteUbergraph_BPUI_Updater final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_Title_1;                        // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_Content_1;                      // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Replace_ReturnValue;                      // 0x0028(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Replace_ReturnValue_1;                    // 0x0038(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Replace_ReturnValue_2;                    // 0x0048(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Replace_ReturnValue_3;                    // 0x0058(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0068(0x0010)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0078(0x0010)()
	class FString                                 K2Node_CustomEvent_Title;                          // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 K2Node_CustomEvent_Content;                        // 0x0098(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Replace_ReturnValue_4;                    // 0x00A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Replace_ReturnValue_5;                    // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Replace_ReturnValue_6;                    // 0x00C8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Replace_ReturnValue_7;                    // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x00E8(0x0010)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_3;          // 0x00F8(0x0010)()
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_109[0x3];                                      // 0x0109(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable;                                 // 0x010C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0110(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0114(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_119[0x3];                                      // 0x0119(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x011C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_NoticeIndex_1;                  // 0x0120(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0124(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_CustomEvent_NoticeIndex;                    // 0x0128(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x012C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_132[0x2];                                      // 0x0132(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0134(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0138(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_2;            // 0x013C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_3;            // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_1;                               // 0x0144(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0148(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_149[0x3];                                      // 0x0149(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const struct FUpdateData& AppUpdateData, const class FText& AppUpdateTips)> K2Node_CreateDelegate_OutputDelegate; // 0x014C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x015C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15D[0x3];                                      // 0x015D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_2;                               // 0x0160(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const struct FUpdateData& AppUpdateData, const class FText& AppUpdateTips)> K2Node_CreateDelegate_OutputDelegate_1; // 0x0164(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_174[0x4];                                      // 0x0174(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0178(0x0010)(ReferenceParm)
	class UWidget*                                K2Node_CustomEvent_BtnWidget_1;                    // 0x0188(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x0190(0x0010)()
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x01A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A1[0x7];                                      // 0x01A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                K2Node_CustomEvent_BtnWidget;                      // 0x01A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_9;               // 0x01B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_8;               // 0x01B8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_7;               // 0x01C0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_6;               // 0x01C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FUpdateData                            K2Node_CustomEvent_AppUpdateData_1;                // 0x01D0(0x0080)(ConstParm)
	class FText                                   K2Node_CustomEvent_AppUpdateTips_1;                // 0x0250(0x0010)(ConstParm)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0260(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x0264(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0265(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue_1;         // 0x0266(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_267[0x1];                                      // 0x0267(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x0268(0x0010)(ReferenceParm)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0278(0x0010)()
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue_2;         // 0x0288(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue_3;         // 0x0289(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_28A[0x6];                                      // 0x028A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FUpdateData                            K2Node_CustomEvent_AppUpdateData;                  // 0x0290(0x0080)(ConstParm)
	class FText                                   K2Node_CustomEvent_AppUpdateTips;                  // 0x0310(0x0010)(ConstParm)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue_4;         // 0x0320(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue_5;         // 0x0321(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_322[0x6];                                      // 0x0322(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_5;               // 0x0328(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	EHTPlatformType                               CallFunc_SwitchPlatform_OutPlatformType;           // 0x0330(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0331(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0332(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x0333(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable_3;                               // 0x0334(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_OpenSource_ReturnValue;                   // 0x0338(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_339[0x7];                                      // 0x0339(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_4;               // 0x0340(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_3;               // 0x0348(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_2;               // 0x0350(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button_1;               // 0x0358(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UCommonButtonBase*                      K2Node_ComponentBoundEvent_Button;                 // 0x0360(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_ExecuteUbergraph_BPUI_Updater;

// Function BPUI_Updater.BPUI_Updater_C.Get_RepairButton_Visibility_0
// 0x0003 (0x0003 - 0x0000)
struct BPUI_Updater_C_Get_RepairButton_Visibility_0 final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHTPlatformType                               CallFunc_SwitchPlatform_OutPlatformType;           // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_Get_RepairButton_Visibility_0;

// Function BPUI_Updater.BPUI_Updater_C.Get_UpdateTextBlock_Text_0
// 0x0010 (0x0010 - 0x0000)
struct BPUI_Updater_C_Get_UpdateTextBlock_Text_0 final
{
public:
	class FText                                   ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm)
};
DUMPER7_ASSERTS_BPUI_Updater_C_Get_UpdateTextBlock_Text_0;

// Function BPUI_Updater.BPUI_Updater_C.InitUITextContent
// 0x0070 (0x0070 - 0x0000)
struct BPUI_Updater_C_InitUITextContent final
{
public:
	TArray<class FText>                           EmptyArgs;                                         // 0x0000(0x0010)(Edit, BlueprintVisible)
	class FText                                   CallFunc_FormatLocalizedText_ReturnValue;          // 0x0010(0x0010)()
	class FText                                   CallFunc_FormatLocalizedText_ReturnValue_1;        // 0x0020(0x0010)()
	class FText                                   CallFunc_FormatLocalizedText_ReturnValue_2;        // 0x0030(0x0010)()
	class FText                                   CallFunc_FormatLocalizedText_ReturnValue_3;        // 0x0040(0x0010)()
	class FText                                   CallFunc_FormatLocalizedText_ReturnValue_4;        // 0x0050(0x0010)()
	class FText                                   CallFunc_FormatLocalizedText_ReturnValue_5;        // 0x0060(0x0010)()
};
DUMPER7_ASSERTS_BPUI_Updater_C_InitUITextContent;

// Function BPUI_Updater.BPUI_Updater_C.OnAppUpdate
// 0x0090 (0x0090 - 0x0000)
struct BPUI_Updater_C_OnAppUpdate final
{
public:
	struct FUpdateData                            AppUpdateData_0;                                   // 0x0000(0x0080)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FText                                   AppUpdateTips_0;                                   // 0x0080(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BPUI_Updater_C_OnAppUpdate;

// Function BPUI_Updater.BPUI_Updater_C.OnClicked_Event_0
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_OnClicked_Event_0 final
{
public:
	class UWidget*                                BtnWidget;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_OnClicked_Event_0;

// Function BPUI_Updater.BPUI_Updater_C.OnClicked_Event_1
// 0x0008 (0x0008 - 0x0000)
struct BPUI_Updater_C_OnClicked_Event_1 final
{
public:
	class UWidget*                                BtnWidget;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_OnClicked_Event_1;

// Function BPUI_Updater.BPUI_Updater_C.OnResUpdateDataChanged_Event
// 0x0090 (0x0090 - 0x0000)
struct BPUI_Updater_C_OnResUpdateDataChanged_Event final
{
public:
	struct FUpdateData                            AppUpdateData_0;                                   // 0x0000(0x0080)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	class FText                                   AppUpdateTips_0;                                   // 0x0080(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_BPUI_Updater_C_OnResUpdateDataChanged_Event;

// Function BPUI_Updater.BPUI_Updater_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct BPUI_Updater_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_PreConstruct;

// Function BPUI_Updater.BPUI_Updater_C.RefreshAppWidget
// 0x0020 (0x0020 - 0x0000)
struct BPUI_Updater_C_RefreshAppWidget final
{
public:
	class FString                                 Title;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Content;                                           // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_RefreshAppWidget;

// Function BPUI_Updater.BPUI_Updater_C.RefreshResWidget
// 0x0020 (0x0020 - 0x0000)
struct BPUI_Updater_C_RefreshResWidget final
{
public:
	class FString                                 Title;                                             // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Content;                                           // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_RefreshResWidget;

// Function BPUI_Updater.BPUI_Updater_C.ShowAppNotice
// 0x0004 (0x0004 - 0x0000)
struct BPUI_Updater_C_ShowAppNotice final
{
public:
	int32                                         NoticeIndex_0;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_ShowAppNotice;

// Function BPUI_Updater.BPUI_Updater_C.ShowWithIndex
// 0x0004 (0x0004 - 0x0000)
struct BPUI_Updater_C_ShowWithIndex final
{
public:
	int32                                         NoticeIndex_0;                                     // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_Updater_C_ShowWithIndex;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
