#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPUI_UpdaterBG

#include "Basic.hpp"

#include "HTGame_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPUI_UpdaterBG.BPUI_UpdaterBG_C.BP_PlayVideo
// 0x0010 (0x0010 - 0x0000)
struct BPUI_UpdaterBG_C_BP_PlayVideo final
{
public:
	class FString                                 VideoUrl;                                          // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_UpdaterBG_C_BP_PlayVideo;

// Function BPUI_UpdaterBG.BPUI_UpdaterBG_C.BP_PlayVideoBGM
// 0x0004 (0x0004 - 0x0000)
struct BPUI_UpdaterBG_C_BP_PlayVideoBGM final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_UpdaterBG_C_BP_PlayVideoBGM;

// Function BPUI_UpdaterBG.BPUI_UpdaterBG_C.ExecuteUbergraph_BPUI_UpdaterBG
// 0x0040 (0x0040 - 0x0000)
struct BPUI_UpdaterBG_C_ExecuteUbergraph_BPUI_UpdaterBG final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EHTPlatformType                               CallFunc_SwitchPlatform_OutPlatformType;           // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17[0x1];                                       // 0x0017(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_Event_VideoUrl;                             // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_index;                                // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostEventGlobal_ReturnValue;              // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_PostEventGlobal_ReturnValue_1;            // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_PostEventGlobal_ReturnValue_2;            // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_UpdaterBG_C_ExecuteUbergraph_BPUI_UpdaterBG;

// Function BPUI_UpdaterBG.BPUI_UpdaterBG_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct BPUI_UpdaterBG_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPUI_UpdaterBG_C_PreConstruct;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
