#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CloudsLighting

#include "Basic.hpp"

#include "CloudsLighting_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function CloudsLighting.CloudsLightingSystem.IsValid
// 0x0001 (0x0001 - 0x0000)
struct CloudsLightingSystem_IsValid final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CloudsLightingSystem_IsValid;

// Function CloudsLighting.VolumetricLightSource.GetType
// 0x0001 (0x0001 - 0x0000)
struct VolumetricLightSource_GetType final
{
public:
	EVLightSourceType                             ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_VolumetricLightSource_GetType;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
