#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CriWareWindowsSettings

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function CriWareWindowsSettings.CriWareWindowsSettings.GetHardwareDeviceOptions
// 0x0010 (0x0010 - 0x0000)
struct CriWareWindowsSettings_GetHardwareDeviceOptions final
{
public:
	TArray<class FString>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_CriWareWindowsSettings_GetHardwareDeviceOptions;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
