#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DynamicRoadKit

#include "Basic.hpp"

#include "DynamicRoadKit_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function DynamicRoadKit.RoadMeshGeneratorComponent.SetRoadLinePoints
// 0x0010 (0x0010 - 0x0000)
struct RoadMeshGeneratorComponent_SetRoadLinePoints final
{
public:
	TArray<struct FTransform>                     InRoadLinePoints;                                  // 0x0000(0x0010)(Parm, ZeroConstructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RoadMeshGeneratorComponent_SetRoadLinePoints;

// Function DynamicRoadKit.RoadNodeComponent.AttachSegment
// 0x0010 (0x0010 - 0x0000)
struct RoadNodeComponent_AttachSegment final
{
public:
	class URoadSegmentComponent*                  Curve;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ConnectorIndex;                                    // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUpdateNode;                                       // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_RoadNodeComponent_AttachSegment;

// Function DynamicRoadKit.RoadNodeComponent.DetachSegment
// 0x0010 (0x0010 - 0x0000)
struct RoadNodeComponent_DetachSegment final
{
public:
	class URoadSegmentComponent*                  Curve;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ConnectorIndex;                                    // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUpdateNode;                                       // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_RoadNodeComponent_DetachSegment;

// Function DynamicRoadKit.RoadNodeComponent.SetAttachSegments
// 0x0018 (0x0018 - 0x0000)
struct RoadNodeComponent_SetAttachSegments final
{
public:
	TArray<struct FRoadNodeAttachment>            InAttachedSegments;                                // 0x0000(0x0010)(Parm, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
	bool                                          bUpdate;                                           // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_RoadNodeComponent_SetAttachSegments;

// Function DynamicRoadKit.RoadNodeComponent.GetAttachedSegmentCalcInfos
// 0x0010 (0x0010 - 0x0000)
struct RoadNodeComponent_GetAttachedSegmentCalcInfos final
{
public:
	TArray<struct FRoadNodeAttachedSegmentCalcInfo> OutInfos;                                        // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RoadNodeComponent_GetAttachedSegmentCalcInfos;

// Function DynamicRoadKit.RoadNodeComponent.GetAttachedSegmentInfos
// 0x0010 (0x0010 - 0x0000)
struct RoadNodeComponent_GetAttachedSegmentInfos final
{
public:
	TArray<struct FRoadSegmentAttachedSegmentInfo> OutInfos;                                         // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RoadNodeComponent_GetAttachedSegmentInfos;

// Function DynamicRoadKit.RoadPrefabNodeActor.GetNumSlots
// 0x0004 (0x0004 - 0x0000)
struct RoadPrefabNodeActor_GetNumSlots final
{
public:
	int32                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RoadPrefabNodeActor_GetNumSlots;

// Function DynamicRoadKit.RoadPrefabNodeActor.GetRoadPrefabNodeDefinition
// 0x0008 (0x0008 - 0x0000)
struct RoadPrefabNodeActor_GetRoadPrefabNodeDefinition final
{
public:
	const class URoadPrefabNodeDataAsset*         ReturnValue;                                       // 0x0000(0x0008)(ConstParm, Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RoadPrefabNodeActor_GetRoadPrefabNodeDefinition;

// Function DynamicRoadKit.RoadPrefabNodeActor.GetSlotWorldTransform
// 0x0070 (0x0070 - 0x0000)
struct RoadPrefabNodeActor_GetSlotWorldTransform final
{
public:
	int32                                         SlotIndex;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0xC];                                        // 0x0004(0x000C)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             ReturnValue;                                       // 0x0010(0x0060)(Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RoadPrefabNodeActor_GetSlotWorldTransform;

// Function DynamicRoadKit.RoadSegmentComponent.SetEndNode
// 0x0010 (0x0010 - 0x0000)
struct RoadSegmentComponent_SetEndNode final
{
public:
	class URoadNodeComponent*                     Node;                                              // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUpdateNode;                                       // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_RoadSegmentComponent_SetEndNode;

// Function DynamicRoadKit.RoadSegmentComponent.SetStartNode
// 0x0010 (0x0010 - 0x0000)
struct RoadSegmentComponent_SetStartNode final
{
public:
	class URoadNodeComponent*                     Node;                                              // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bUpdateNode;                                       // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_RoadSegmentComponent_SetStartNode;

// Function DynamicRoadKit.RoadSegmentComponent.GetCurveData
// 0x0078 (0x0078 - 0x0000)
struct RoadSegmentComponent_GetCurveData final
{
public:
	struct FRoadSegmentData                       OutCurveData;                                      // 0x0000(0x0078)(Parm, OutParm, ContainsInstancedReference, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_RoadSegmentComponent_GetCurveData;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
