#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FluidFlux

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// Class FluidFlux.FluidFluxActor
// 0x0000 (0x02C8 - 0x02C8)
class AFluidFluxActor final : public AActor
{
public:
	bool IsES3_1();
	void WhenFeatureLevelChanged();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("FluidFluxActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"FluidFluxActor")
	}
	static class AFluidFluxActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFluidFluxActor>();
	}
};
DUMPER7_ASSERTS_AFluidFluxActor;

SDK_NAMESPACE_END
