#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HTStartupLoadingScreen

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum HTStartupLoadingScreen.EHTMovieScreenPlaybackType
// NumValues: 0x0004
enum class EHTMovieScreenPlaybackType : uint8
{
	MT_MS_Normal                             = 0,
	MT_MS_Looped                             = 1,
	MT_MS_LoadingLoop                        = 2,
	MT_MS_MAX                                = 3,
};

SDK_NAMESPACE_END
