#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HTWorldPartition

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function HTWorldPartition.HTTransformerISMEditorUtilityObject.GetBreakableMeshs
// 0x0010 (0x0010 - 0x0000)
struct HTTransformerISMEditorUtilityObject_GetBreakableMeshs final
{
public:
	TArray<class UStaticMesh*>                    ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_HTTransformerISMEditorUtilityObject_GetBreakableMeshs;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
