#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoginPlayerAnimBlueprint_Male

#include "Basic.hpp"

#include "LoginPlayerAnimBlueprint_classes.hpp"


SDK_NAMESPACE_START

// AnimBlueprintGeneratedClass LoginPlayerAnimBlueprint_Male.LoginPlayerAnimBlueprint_Male_C
// 0x0000 (0x05F0 - 0x05F0)
class ULoginPlayerAnimBlueprint_Male_C final : public ULoginPlayerAnimBlueprint_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LoginPlayerAnimBlueprint_Male_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LoginPlayerAnimBlueprint_Male_C")
	}
	static class ULoginPlayerAnimBlueprint_Male_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULoginPlayerAnimBlueprint_Male_C>();
	}
};
DUMPER7_ASSERTS_ULoginPlayerAnimBlueprint_Male_C;

SDK_NAMESPACE_END
