#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoginPlayerAnimBlueprint_Male

#include "Basic.hpp"

#include "LoginPlayerAnimBlueprint_structs.hpp"


SDK_NAMESPACE_START

// ScriptStruct LoginPlayerAnimBlueprint_Male.LoginPlayerAnimBlueprint_Male_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x02A0 - 0x02A0)
struct LoginPlayerAnimBlueprint_Male::FAnimBlueprintGeneratedConstantData final : public LoginPlayerAnimBlueprint::FAnimBlueprintGeneratedConstantData
{
};
DUMPER7_ASSERTS_LoginPlayerAnimBlueprint_Male__FAnimBlueprintGeneratedConstantData;

SDK_NAMESPACE_END
