#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewBlueprint_queue

#include "Basic.hpp"

#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass NewBlueprint_queue.NewBlueprint_queue_C
// 0x0000 (0x0370 - 0x0370)
class UNewBlueprint_queue_C final : public UHTAIIdleStateBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NewBlueprint_queue_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NewBlueprint_queue_C")
	}
	static class UNewBlueprint_queue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNewBlueprint_queue_C>();
	}
};
DUMPER7_ASSERTS_UNewBlueprint_queue_C;

SDK_NAMESPACE_END
