#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewBlueprint_noisetalk_1

#include "Basic.hpp"

#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass NewBlueprint_noisetalk_1.NewBlueprint_noisetalk_1_C
// 0x0000 (0x0370 - 0x0370)
class UNewBlueprint_noisetalk_1_C : public UHTAIIdleStateBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NewBlueprint_noisetalk_1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NewBlueprint_noisetalk_1_C")
	}
	static class UNewBlueprint_noisetalk_1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNewBlueprint_noisetalk_1_C>();
	}
};
DUMPER7_ASSERTS_UNewBlueprint_noisetalk_1_C;

SDK_NAMESPACE_END
