#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Oceanology_Plugin

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum Oceanology_Plugin.EInfinityCategory
// NumValues: 0x0002
enum class EInfinityCategory : uint8
{
	InfiniteOcean                            = 0,
	EInfinityCategory_MAX                    = 1,
};

SDK_NAMESPACE_END
