#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UDS_Weather_Override_Mode

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum UDS_Weather_Override_Mode.UDS_Weather_Override_Mode
// NumValues: 0x0003
enum class EUDS_Weather_Override_Mode : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	UDS_Weather_Override_MAX                 = 2,
};

SDK_NAMESPACE_END
