#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Updater_P

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass Updater_P.Updater_P_C
// 0x0040 (0x0318 - 0x02D8)
class AUpdater_P_C final : public AHTLevelScriptActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ASpotLight*                             SpotLight_0_ExecuteUbergraph_Updater_P_RefProperty; // 0x02E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASpotLight*                             SpotLight_1_ExecuteUbergraph_Updater_P_RefProperty; // 0x02E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASpotLight*                             SpotLight_2_ExecuteUbergraph_Updater_P_RefProperty; // 0x02F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASpotLight*                             SpotLight_3_ExecuteUbergraph_Updater_P_RefProperty; // 0x02F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASpotLight*                             SpotLight_4_ExecuteUbergraph_Updater_P_RefProperty; // 0x0300(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASpotLight*                             SpotLight_9_ExecuteUbergraph_Updater_P_RefProperty; // 0x0308(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ASpotLight*                             SpotLight_8_ExecuteUbergraph_Updater_P_RefProperty; // 0x0310(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_Updater_P(int32 EntryPoint);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Updater_P_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Updater_P_C")
	}
	static class AUpdater_P_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AUpdater_P_C>();
	}
};
DUMPER7_ASSERTS_AUpdater_P_C;

SDK_NAMESPACE_END
