#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Updater_P

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function Updater_P.Updater_P_C.ExecuteUbergraph_Updater_P
// 0x0008 (0x0008 - 0x0000)
struct Updater_P_C_ExecuteUbergraph_Updater_P final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPreviewMobile_ReturnValue;              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Updater_P_C_ExecuteUbergraph_Updater_P;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
