#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_BoundActionButton_PopupClose

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "HTGame_classes.hpp"
#include "SlateCore_structs.hpp"
#include "CommonInput_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass W_BoundActionButton_PopupClose.W_BoundActionButton_PopupClose_C
// 0x0040 (0x15F0 - 0x15B0)
class UW_BoundActionButton_PopupClose_C final : public UHTBoundActionButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x15B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_Glow_H;                                      // 0x15B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Glow_A;                                      // 0x15C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Close_1;                                     // 0x15C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Close;                                       // 0x15D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_70;                                          // 0x15D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                ButtonBorder;                                      // 0x15E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsDisabled;                                        // 0x15E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnClicked();
	void BP_OnDeselected();
	void BP_OnDisabled();
	void BP_OnEnabled();
	void BP_OnHovered();
	void BP_OnPressed();
	void BP_OnReleased();
	void BP_OnSelected();
	void BP_OnUnhovered();
	void Construct();
	void Destruct();
	void Event_Input_Method_Changed(ECommonInputType bNewInputType);
	void ExecuteUbergraph_W_BoundActionButton_PopupClose(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void ResetMaterials();
	void UpdateSyleOnInputMethod(ECommonInputType InputType);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_BoundActionButton_PopupClose_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_BoundActionButton_PopupClose_C")
	}
	static class UW_BoundActionButton_PopupClose_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_BoundActionButton_PopupClose_C>();
	}
};
DUMPER7_ASSERTS_UW_BoundActionButton_PopupClose_C;

SDK_NAMESPACE_END
